"""Tests for the four Lambda export handlers.

We invoke each handler directly with an API-Gateway-shaped event dict
— no FastAPI, no TestClient. The sample-source layer is stubbed
exactly as in the per-target tests so nothing reaches the gist or
S3.
"""
from __future__ import annotations

import base64
import io
import json
import os
import unittest
import zipfile

from app.api.ot_basic.handler import handler as ot_basic_handler
from app.api.ot_doom.handler import handler as ot_doom_handler
from app.api.strudel.handler import handler as strudel_handler
from app.api.torso_s4.handler import handler as torso_s4_handler

from tests.export._fixtures import (
    WorkDir,
    make_break_wavs,
    make_capture_cell,
    make_export,
    make_per_track_break_wavs,
)


def _event(body: dict, *, headers: dict | None = None) -> dict:
    return {
        'headers': headers or {},
        'body': json.dumps(body),
    }


def _basic_header(token: str) -> dict:
    return {'authorization': 'Basic ' + base64.b64encode(token.encode()).decode()}


class StrudelHandlerTest(unittest.TestCase):
    def test_returns_js_with_filename(self):
        payload = make_export([[
            make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
        ]])
        r = strudel_handler(_event({'payload': payload, 'name': 'TESTNAME'}))
        self.assertEqual(r['statusCode'], 200)
        self.assertEqual(r['headers']['Content-Type'], 'application/javascript')
        self.assertIn('TESTNAME.strudel.js', r['headers']['Content-Disposition'])
        self.assertIn('// Generated by', r['body'])
        self.assertIn('strudel.json', r['body'])

    def test_missing_payload_400(self):
        r = strudel_handler(_event({'name': 'X'}))
        self.assertEqual(r['statusCode'], 400)


class OtBasicHandlerTest(unittest.TestCase):
    def test_returns_zip(self):
        with WorkDir() as wd:
            paths = make_per_track_break_wavs(
                wd.samples, ['kk'], tracks=('kick', 'snare', 'hat'),
                bpm=120, steps=32,
            )
            wd.stub_sources(paths)

            payload = make_export([[
                make_capture_cell(['kk'], [0, 1, 2, 3, 4, 5, 6, 7]),
            ]])
            r = ot_basic_handler(_event({'payload': payload, 'name': 'OTB'}))
            self.assertEqual(r['statusCode'], 200, r.get('body'))
            self.assertEqual(r['headers']['Content-Type'], 'application/zip')
            self.assertIn('OTB.ot.zip', r['headers']['Content-Disposition'])
            self.assertTrue(r.get('isBase64Encoded'))
            data = base64.b64decode(r['body'])
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                self.assertTrue(any(n.endswith('.work') for n in zf.namelist()))


class TorsoS4HandlerTest(unittest.TestCase):
    def test_returns_zip(self):
        with WorkDir() as wd:
            paths = make_break_wavs(wd.samples, ['a'], bpm=120, steps=32)
            wd.stub_sources(paths)

            payload = make_export([[
                make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
            ]])
            r = torso_s4_handler(_event({'payload': payload, 'name': 'S4P'}))
            self.assertEqual(r['statusCode'], 200, r.get('body'))
            self.assertEqual(r['headers']['Content-Type'], 'application/zip')
            self.assertIn('S4P.s4.zip', r['headers']['Content-Disposition'])
            data = base64.b64decode(r['body'])
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                wavs = [n for n in zf.namelist() if n.endswith('.wav')]
                self.assertTrue(wavs)
                self.assertTrue(all(n.startswith('S4P/') for n in wavs))


class AuthTest(unittest.TestCase):
    """Auth gate is identical across handlers — exercise it once on
    the strudel handler (cheapest / no audio render)."""

    def setUp(self):
        os.environ['AUTH_TOKEN'] = 'u:p'

    def tearDown(self):
        os.environ.pop('AUTH_TOKEN', None)

    def test_missing_header_401(self):
        r = strudel_handler(_event({'payload': {}}, headers={}))
        self.assertEqual(r['statusCode'], 401)
        self.assertEqual(r['headers']['WWW-Authenticate'], 'Basic')

    def test_bad_creds_401(self):
        r = strudel_handler(_event(
            {'payload': {}}, headers=_basic_header('u:wrong'),
        ))
        self.assertEqual(r['statusCode'], 401)

    def test_good_creds_pass_through(self):
        payload = make_export([[
            make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
        ]])
        r = strudel_handler(_event(
            {'payload': payload, 'name': 'AUTHED'},
            headers=_basic_header('u:p'),
        ))
        self.assertEqual(r['statusCode'], 200)


if __name__ == '__main__':
    unittest.main()
