"""Tests for the five Lambda handlers.

We invoke each handler directly with an API-Gateway-shaped event dict
— no FastAPI, no TestClient. The sample-source layer is stubbed
exactly as in the per-target tests so nothing reaches the gist or
S3.
"""
from __future__ import annotations

import base64
import io
import json
import os
import unittest
import zipfile

from app.api.launch.handler import handler as launch_handler
from app.api.ot_basic.handler import handler as ot_basic_handler
from app.api.ot_doom.handler import handler as ot_doom_handler
from app.api.strudel.handler import handler as strudel_handler
from app.api.torso_s4.handler import handler as torso_s4_handler

from tests.export._fixtures import (
    WorkDir,
    make_break_wavs,
    make_capture_cell,
    make_export,
    make_per_track_break_wavs,
)


def _event(body: dict, *, headers: dict | None = None) -> dict:
    return {
        'headers': headers or {},
        'body': json.dumps(body),
    }


def _basic_header(token: str) -> dict:
    return {'authorization': 'Basic ' + base64.b64encode(token.encode()).decode()}


class StrudelHandlerTest(unittest.TestCase):
    def test_returns_js_with_filename(self):
        payload = make_export([[
            make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
        ]])
        r = strudel_handler(_event({'payload': payload, 'name': 'TESTNAME'}))
        self.assertEqual(r['statusCode'], 200)
        self.assertEqual(r['headers']['Content-Type'], 'application/javascript')
        self.assertIn('TESTNAME.strudel.js', r['headers']['Content-Disposition'])
        self.assertIn('// Generated by', r['body'])
        self.assertIn('strudel.json', r['body'])

    def test_missing_payload_400(self):
        r = strudel_handler(_event({'name': 'X'}))
        self.assertEqual(r['statusCode'], 400)


class OtBasicHandlerTest(unittest.TestCase):
    def test_returns_zip(self):
        with WorkDir() as wd:
            paths = make_per_track_break_wavs(
                wd.samples, ['kk'], tracks=('kick', 'snare', 'hat'),
                bpm=120, steps=32,
            )
            wd.stub_sources(paths)

            payload = make_export([[
                make_capture_cell(['kk'], [0, 1, 2, 3, 4, 5, 6, 7]),
            ]])
            r = ot_basic_handler(_event({'payload': payload, 'name': 'OTB'}))
            self.assertEqual(r['statusCode'], 200, r.get('body'))
            self.assertEqual(r['headers']['Content-Type'], 'application/zip')
            self.assertIn('OTB.ot.zip', r['headers']['Content-Disposition'])
            self.assertTrue(r.get('isBase64Encoded'))
            data = base64.b64decode(r['body'])
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                self.assertTrue(any(n.endswith('.work') for n in zf.namelist()))

    def test_accepts_flatten_flag(self):
        with WorkDir() as wd:
            paths = make_per_track_break_wavs(
                wd.samples, ['kk'], tracks=('kick', 'snare', 'hat'),
                bpm=120, steps=32,
            )
            wd.stub_sources(paths)
            payload = make_export([[
                make_capture_cell(['kk'], [0, 1, 2, 3, 4, 5, 6, 7]),
            ]])
            r = ot_basic_handler(_event({
                'payload': payload, 'name': 'OTB2',
                'flatten': True,
            }))
            self.assertEqual(r['statusCode'], 200, r.get('body'))

    def test_rejects_non_bool_flatten(self):
        r = ot_basic_handler(_event({
            'payload': {}, 'name': 'X', 'flatten': 'yes',
        }))
        self.assertEqual(r['statusCode'], 400)
        self.assertIn('flatten', r['body'])


class TorsoS4HandlerTest(unittest.TestCase):
    def test_returns_zip(self):
        with WorkDir() as wd:
            paths = make_break_wavs(wd.samples, ['a'], bpm=120, steps=32)
            wd.stub_sources(paths)

            payload = make_export([[
                make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
            ]])
            r = torso_s4_handler(_event({'payload': payload, 'name': 'S4P'}))
            self.assertEqual(r['statusCode'], 200, r.get('body'))
            self.assertEqual(r['headers']['Content-Type'], 'application/zip')
            self.assertIn('S4P.s4.zip', r['headers']['Content-Disposition'])
            data = base64.b64decode(r['body'])
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                wavs = [n for n in zf.namelist() if n.endswith('.wav')]
                self.assertTrue(wavs)
                self.assertTrue(all(n.startswith('S4P/') for n in wavs))


class AuthTest(unittest.TestCase):
    """Auth gate is identical across handlers — exercise it once on
    the strudel handler (cheapest / no audio render)."""

    def setUp(self):
        os.environ['AUTH_TOKEN'] = 'u:p'

    def tearDown(self):
        os.environ.pop('AUTH_TOKEN', None)

    def test_missing_header_401(self):
        r = strudel_handler(_event({'payload': {}}, headers={}))
        self.assertEqual(r['statusCode'], 401)
        self.assertEqual(r['headers']['WWW-Authenticate'], 'Basic')

    def test_bad_creds_401(self):
        r = strudel_handler(_event(
            {'payload': {}}, headers=_basic_header('u:wrong'),
        ))
        self.assertEqual(r['statusCode'], 401)

    def test_good_creds_pass_through(self):
        payload = make_export([[
            make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
        ]])
        r = strudel_handler(_event(
            {'payload': payload, 'name': 'AUTHED'},
            headers=_basic_header('u:p'),
        ))
        self.assertEqual(r['statusCode'], 200)


class LaunchHandlerTest(unittest.TestCase):
    """The launch handler is the only one that responds to GET, returns
    a 302, reads the bundled tempera.strudel.js, and rewrites four
    `const` literals from query string + env. Cover each rewrite path
    + the auth gate."""

    @staticmethod
    def _event(qs=None, headers=None, domain='strudelbeats.klingklangwol.com'):
        return {
            'queryStringParameters': qs,
            'headers': headers or {},
            'requestContext': {'domainName': domain} if domain else {},
        }

    @staticmethod
    def _decode_payload(redirect_url):
        # `https://strudel.cc/#<base64>` → decoded JS source
        prefix = 'https://strudel.cc/#'
        assert redirect_url.startswith(prefix), redirect_url
        return base64.b64decode(redirect_url[len(prefix):]).decode('utf-8')

    def test_default_serves_committed_literals(self):
        r = launch_handler(self._event())
        self.assertEqual(r['statusCode'], 302)
        src = self._decode_payload(r['headers']['Location'])
        self.assertIn("const gistUser = 'jhw';", src)
        self.assertIn('const BPM = 124;', src)
        self.assertIn('const SEED = 22682;', src)
        # SERVER_URL gets baked from requestContext.domainName even
        # when no override is supplied.
        self.assertIn(
            "const SERVER_URL = 'https://strudelbeats.klingklangwol.com';",
            src,
        )

    def test_server_url_from_host_header_when_no_request_context(self):
        r = launch_handler(self._event(
            headers={'host': 'fallback.example.com'}, domain=None,
        ))
        src = self._decode_payload(r['headers']['Location'])
        self.assertIn(
            "const SERVER_URL = 'https://fallback.example.com';", src,
        )

    def test_auth_header_baked_when_token_set(self):
        os.environ['AUTH_TOKEN'] = 'me:secret'
        try:
            r = launch_handler(self._event(headers=_basic_header('me:secret')))
            self.assertEqual(r['statusCode'], 302)
            src = self._decode_payload(r['headers']['Location'])
            expected = 'Basic ' + base64.b64encode(b'me:secret').decode()
            self.assertIn(f"const AUTH_HEADER = '{expected}';", src)
        finally:
            os.environ.pop('AUTH_TOKEN', None)

    def test_auth_header_left_empty_when_token_unset(self):
        # No AUTH_TOKEN → AUTH_HEADER literal stays as the empty default.
        r = launch_handler(self._event())
        src = self._decode_payload(r['headers']['Location'])
        self.assertIn("const AUTH_HEADER = '';", src)

    def test_query_overrides_apply(self):
        r = launch_handler(self._event(qs={
            'gistUser': 'someone', 'gistId': 'abc123', 'bpm': '140', 'seed': '7',
        }))
        self.assertEqual(r['statusCode'], 302)
        src = self._decode_payload(r['headers']['Location'])
        self.assertIn("const gistUser = 'someone';", src)
        self.assertIn("const gistId = 'abc123';", src)
        self.assertIn('const BPM = 140;', src)
        self.assertIn('const SEED = 7;', src)

    def test_env_defaults_apply_when_query_absent(self):
        os.environ['LAUNCH_GIST_USER'] = 'envman'
        os.environ['LAUNCH_BPM'] = '160'
        try:
            r = launch_handler(self._event())
            src = self._decode_payload(r['headers']['Location'])
            self.assertIn("const gistUser = 'envman';", src)
            self.assertIn('const BPM = 160;', src)
        finally:
            os.environ.pop('LAUNCH_GIST_USER', None)
            os.environ.pop('LAUNCH_BPM', None)

    def test_query_wins_over_env(self):
        os.environ['LAUNCH_BPM'] = '100'
        try:
            r = launch_handler(self._event(qs={'bpm': '170'}))
            src = self._decode_payload(r['headers']['Location'])
            self.assertIn('const BPM = 170;', src)
        finally:
            os.environ.pop('LAUNCH_BPM', None)

    def test_invalid_query_returns_400(self):
        r = launch_handler(self._event(qs={'gistUser': 'has spaces'}))
        self.assertEqual(r['statusCode'], 400)

    def test_auth_gate(self):
        os.environ['AUTH_TOKEN'] = 'u:p'
        try:
            r = launch_handler(self._event())
            self.assertEqual(r['statusCode'], 401)
            self.assertEqual(r['headers']['WWW-Authenticate'], 'Basic')

            r = launch_handler(self._event(headers=_basic_header('u:p')))
            self.assertEqual(r['statusCode'], 302)
        finally:
            os.environ.pop('AUTH_TOKEN', None)


class LaunchStoredDefaultsTest(unittest.TestCase):
    """`/launch` persists validated query-string args to a single S3
    key and reads them back on subsequent visits when the query
    string is empty. The S3 client is patched per-test so nothing
    reaches AWS."""

    URI = 's3://test-artifacts/launch-defaults/global.json'

    def setUp(self):
        os.environ['LAUNCH_DEFAULTS_S3_URI'] = self.URI
        # Backing store the per-test fake s3 client reads/writes.
        self.store: dict = {}
        self._patch_boto3()

    def tearDown(self):
        os.environ.pop('LAUNCH_DEFAULTS_S3_URI', None)
        self._unpatch_boto3()

    def _patch_boto3(self):
        # Inject a fake boto3 module the handler picks up via its
        # deferred `import boto3`. Behaves enough like the real
        # client to drive the get/put paths.
        import sys
        import types

        store = self.store

        class _NoSuchKey(Exception):
            response = {'Error': {'Code': 'NoSuchKey'}}

        class _FakeClient:
            def get_object(self, *, Bucket, Key):
                if (Bucket, Key) not in store:
                    raise _NoSuchKey()
                payload = store[(Bucket, Key)]
                return {'Body': type('B', (), {'read': lambda _self: payload})()}

            def put_object(self, *, Bucket, Key, Body, ContentType=None):
                store[(Bucket, Key)] = Body

        fake_boto3 = types.ModuleType('boto3')
        fake_boto3.client = lambda name: _FakeClient()
        fake_botocore = types.ModuleType('botocore')
        fake_exceptions = types.ModuleType('botocore.exceptions')
        fake_exceptions.ClientError = _NoSuchKey
        fake_botocore.exceptions = fake_exceptions

        self._saved = {
            'boto3': sys.modules.get('boto3'),
            'botocore': sys.modules.get('botocore'),
            'botocore.exceptions': sys.modules.get('botocore.exceptions'),
        }
        sys.modules['boto3'] = fake_boto3
        sys.modules['botocore'] = fake_botocore
        sys.modules['botocore.exceptions'] = fake_exceptions

    def _unpatch_boto3(self):
        import sys
        for name, mod in self._saved.items():
            if mod is None:
                sys.modules.pop(name, None)
            else:
                sys.modules[name] = mod

    @staticmethod
    def _event(qs=None):
        return {
            'queryStringParameters': qs,
            'headers': {},
            'requestContext': {'domainName': 'strudelbeats.example.com'},
        }

    @staticmethod
    def _decode_payload(redirect_url):
        prefix = 'https://strudel.cc/#'
        return base64.b64decode(redirect_url[len(prefix):]).decode('utf-8')

    def test_qs_values_persist_to_s3(self):
        # First call with a qs: validated values land in the store.
        r = launch_handler(self._event(qs={
            'gistUser': 'alice', 'gistId': 'feed', 'bpm': '140', 'seed': '99',
        }))
        self.assertEqual(r['statusCode'], 302)
        self.assertEqual(len(self.store), 1)
        ((bucket, key), body), = self.store.items()
        self.assertEqual(bucket, 'test-artifacts')
        self.assertEqual(key, 'launch-defaults/global.json')
        self.assertEqual(json.loads(body), {
            'gistUser': 'alice', 'gistId': 'feed', 'bpm': '140', 'seed': '99',
        })

    def test_no_qs_uses_stored_defaults(self):
        # Pre-seed the store as if a previous visit had supplied values.
        self.store[('test-artifacts', 'launch-defaults/global.json')] = json.dumps({
            'gistUser': 'persisted', 'gistId': 'cafef00d',
            'bpm': '155', 'seed': '7',
        }).encode()
        r = launch_handler(self._event())
        self.assertEqual(r['statusCode'], 302)
        src = self._decode_payload(r['headers']['Location'])
        self.assertIn("const gistUser = 'persisted';", src)
        self.assertIn("const gistId = 'cafef00d';", src)
        self.assertIn('const BPM = 155;', src)
        self.assertIn('const SEED = 7;', src)

    def test_qs_wins_over_stored_and_persists(self):
        # Stored has bpm=100; qs supplies bpm=170. The redirect uses
        # 170 *and* the new bpm overwrites the stored value.
        self.store[('test-artifacts', 'launch-defaults/global.json')] = json.dumps({
            'gistUser': 'old', 'bpm': '100',
        }).encode()
        r = launch_handler(self._event(qs={'bpm': '170'}))
        src = self._decode_payload(r['headers']['Location'])
        self.assertIn('const BPM = 170;', src)
        # Stored gistUser stays — partial overrides accumulate.
        self.assertIn("const gistUser = 'old';", src)
        body = self.store[('test-artifacts', 'launch-defaults/global.json')]
        self.assertEqual(json.loads(body), {'gistUser': 'old', 'bpm': '170'})

    def test_stored_wins_over_env(self):
        # Resolution order: qs > stored > env. With no qs, stored beats env.
        self.store[('test-artifacts', 'launch-defaults/global.json')] = json.dumps({
            'bpm': '155',
        }).encode()
        os.environ['LAUNCH_BPM'] = '100'
        try:
            r = launch_handler(self._event())
            src = self._decode_payload(r['headers']['Location'])
            self.assertIn('const BPM = 155;', src)
        finally:
            os.environ.pop('LAUNCH_BPM', None)

    def test_env_used_when_no_qs_and_no_stored(self):
        os.environ['LAUNCH_BPM'] = '160'
        try:
            r = launch_handler(self._event())
            src = self._decode_payload(r['headers']['Location'])
            self.assertIn('const BPM = 160;', src)
            # No qs → nothing persisted (env defaults stay out of the
            # stored blob so they're easy to change centrally).
            self.assertEqual(self.store, {})
        finally:
            os.environ.pop('LAUNCH_BPM', None)

    def test_invalid_qs_does_not_persist(self):
        # qs validation runs before persistence; a 400 must not write.
        r = launch_handler(self._event(qs={'gistUser': 'has spaces'}))
        self.assertEqual(r['statusCode'], 400)
        self.assertEqual(self.store, {})

    def test_no_uri_skips_s3_entirely(self):
        # If LAUNCH_DEFAULTS_S3_URI is unset (e.g. local dev / tests
        # without infra) the handler must work as if persistence
        # didn't exist — no read attempts, no write attempts.
        os.environ.pop('LAUNCH_DEFAULTS_S3_URI', None)
        r = launch_handler(self._event(qs={'bpm': '140'}))
        self.assertEqual(r['statusCode'], 302)
        self.assertEqual(self.store, {})


if __name__ == '__main__':
    unittest.main()
