"""End-to-end tests for the FastAPI export server.

Each test stubs `common.sample_source.resolve_break_paths` (no S3, no
gist fetch) and POSTs a tiny captures payload to the server. We
assert on status, Content-Disposition filename suffix, and that the
binary targets really hand back zip bytes.

Skipped wholesale if `fastapi` isn't installed, so the existing
export-target tests keep running on a stripped-down env.
"""
from __future__ import annotations

import importlib
import io
import sys
import unittest
import zipfile

try:
    from fastapi.testclient import TestClient  # type: ignore
    HAS_FASTAPI = True
except Exception:  # pragma: no cover
    HAS_FASTAPI = False

from tests.export._fixtures import (
    WorkDir,
    make_capture_cell,
    make_export,
    make_break_wavs,
    make_per_track_break_wavs,
)


@unittest.skipUnless(HAS_FASTAPI, 'fastapi not installed')
class ServerExportTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Force a fresh import so any sys.path tweaks made by tests
        # earlier in the run don't leak in.
        for mod in list(sys.modules):
            if mod.startswith('app.'):
                sys.modules.pop(mod, None)
        from app.main import app  # noqa: F401  (registers routes)
        cls.client = TestClient(app)

    def test_text_strudel_returns_js_with_filename(self):
        payload = make_export([[
            make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
        ]])
        r = self.client.post('/api/export/text', json={
            'target': 'strudel', 'payload': payload, 'name': 'TESTNAME',
        })
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.headers['content-type'], 'application/javascript')
        self.assertIn('TESTNAME.strudel.js',
                      r.headers.get('content-disposition', ''))
        self.assertIn('// Generated by', r.text)
        self.assertIn('strudel.json', r.text)

    def test_text_unknown_target_400(self):
        r = self.client.post('/api/export/text', json={
            'target': 'lua-rocks', 'payload': {}, 'name': 'X',
        })
        self.assertEqual(r.status_code, 400)

    def test_binary_ot_basic_returns_zip(self):
        with WorkDir() as wd:
            paths = make_per_track_break_wavs(
                wd.samples, ['kk'], tracks=('kick', 'snare', 'hat'),
                bpm=120, steps=32,
            )
            wd.stub_sources(paths)

            payload = make_export([[
                make_capture_cell(['kk'], [0, 1, 2, 3, 4, 5, 6, 7]),
            ]])
            r = self.client.post('/api/export/binary', json={
                'target': 'ot-basic', 'payload': payload, 'name': 'OTB',
            })
            self.assertEqual(r.status_code, 200, r.text)
            self.assertEqual(r.headers['content-type'], 'application/zip')
            self.assertIn('OTB.ot.zip',
                          r.headers.get('content-disposition', ''))
            with zipfile.ZipFile(io.BytesIO(r.content)) as zf:
                self.assertTrue(any(n.endswith('.work') for n in zf.namelist()))

    def test_binary_torso_s4_returns_zip(self):
        with WorkDir() as wd:
            paths = make_break_wavs(wd.samples, ['a'], bpm=120, steps=32)
            wd.stub_sources(paths)

            payload = make_export([[
                make_capture_cell(['a'], [0, 1, 2, 3, 4, 5, 6, 7]),
            ]])
            r = self.client.post('/api/export/binary', json={
                'target': 'torso-s4', 'payload': payload, 'name': 'S4P',
            })
            self.assertEqual(r.status_code, 200, r.text)
            self.assertEqual(r.headers['content-type'], 'application/zip')
            self.assertIn('S4P.s4.zip',
                          r.headers.get('content-disposition', ''))
            with zipfile.ZipFile(io.BytesIO(r.content)) as zf:
                wavs = [n for n in zf.namelist() if n.endswith('.wav')]
                self.assertTrue(wavs)
                self.assertTrue(all(n.startswith('S4P/') for n in wavs))

    def test_binary_unknown_target_400(self):
        r = self.client.post('/api/export/binary', json={
            'target': 'nintendo-ds', 'payload': {}, 'name': 'X',
        })
        self.assertEqual(r.status_code, 400)


if __name__ == '__main__':
    unittest.main()
